function formatCurrency(val) {
  const formatterCurrency = new Intl.NumberFormat("pt-MZ", {
    style: "decimal",
    currency: "MZN",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

  return formatterCurrency.format(val);
}

const courses = [
  {
    id: 1,
    label: "Contabilidade + Primavera",
    icon: '📊',
    duration: '3 MESES',
    price: 2600,
    colors: ["#ff2276"],
    plan: "contabilidade-primavera.html",
    show: true,
  },
  {
    id: 2,
    label: "Marketing Digital",
    icon: '📢',
    duration: '2 SEMANAS',
    price: 1200,
    colors: ["#af23c3"],
    plan: 'marketing-digital.html',
    show: true,
  },
  {
    id: 3,
    label: "Excel básico à avançado",
    icon: '📊',
    duration: '2 MESES',
    price: 2100,
    colors: ["#2DAA73"],
    plan: 'excel-basico-ao-avancado.html',
    show: true,
  },
  {
    id: 4,
    label: "Recrutamento e selecção",
    icon: '🧑‍💼',
    duration: '1 MÊS',
    price: 1750,
    colors: ["#823ba2"],
    plan: 'excel-basico-ao-avancado.html',
    show: true,
  },
  {
    id: 5,
    label: "Atendimento ao cliente",
    icon: '🤝',
    duration: '3 SEMANAS',
    price: 1550,
    colors: ["#1f0a48"],
    plan: 'atendimento-ao-cliente.html',
    show: true,
  },
  {
    id: 6,
    label: "Técnicas de venda",
    icon: '💰',
    duration: '3 SEMANAS',
    price: 1100,
    colors: ["#581105"],
    plan: 'tecnicas-de-venda.html',
    show: true,
  },
  {
    id: 7,
    label: "Electricidade instaladora",
    icon: '⚡',
    duration: '3 MESES',
    price: 2700,
    colors: ["orange"],
    plan: 'electricidade-instaladora.html',
    show: true,
  },
  {
    id: 8,
    label: "Inglês técnico",
    icon: '🌍',
    duration: '2 MESES',
    price: 1600,
    colors: ["#122030"],
    plan: 'ingles-tecnico.html',
    show: true,
  },
  {
    id: 9,
    label: "Redes de computadores",
    icon: '🌐',
    duration: '3 MESES',
    price: 1950,
    colors: ["#1ba0d2"],
    plan: 'redes-de-computadores.html',
    show: true,
  },
  {
    id: 10,
    label: "Design",
    icon: '🎨',
    duration: '2 SEMANAS',
    price: 1200,
    colors: ["#191ae8"],
    plan: 'design.html',
    show: true,
  },
  {
    id: 11,
    label: "Edição de vídeos",
    icon: '🎬',
    duration: '3 SEMANAS',
    price: 1600,
    colors: ["#502390"],
    plan: 'edicao-de-videos.html',
    show: true,
  },
  {
    id: 12,
    label: "Higiene, Saúde e segurança no trabalho (HSST)",
    icon: '🦺',
    duration: '2 MESES',
    price: 2350,
    colors: ["#ce3b74"],
    plan: 'hsst.html',
    show: true,
  },
  {
    id: 13,
    label: "Fundamentos de programação",
    icon: '🧑🏽‍💻',
    duration: '2 MESES',
    price: 1550,
    colors: ["#ae2be7"],
    plan: 'fundamentos-de-programacao.html',
    show: true,
  },
  {
    id: 14,
    label: "Bases de dados",
    icon: '🧑🏽‍💻',
    duration: '1 MÊS',
    price: 1550,
    colors: ["#ce2ce2"],
    plan: 'base-de-dados.html',
    show: true,
  },
  {
    id: 15,
    label: "Gestão de projectos",
    icon: '👩🏽‍💻',
    duration: '2 MESES',
    price: 2700,
    colors: ["#0a688b"],
    plan: 'gestao-de-projectos.html',
    show: true,
  },
  {
    id: 16,
    label: "CCTV",
    icon: '📹',
    duration: '2 MESES',
    price: 2700,
    colors: ["#32164f"],
    plan: 'cctv.html',
    show: true,
  },
  {
    id: 17,
    label: "Monitoria e avaliação",
    icon: '👩‍🏫',
    duration: '6 MESES',
    price: 2700,
    colors: ["#04ab8f"],
    plan: 'cctv.html',
    show: true,
  },
  {
    id: 18,
    label: "Gestão Empresarial",
    icon: '🏢',
    duration: '6 MESES',
    price: 2700,
    colors: ["#0d4e6a"],
    plan: 'cctv.html',
    show: true,
  },
  {
    id: 19,
    label: "Electricidade auto",
    icon: '⚡🚘',
    duration: '3 MESES',
    price: 2700,
    colors: ["gold"],
    plan: '',
    show: true,
  },
  {
    id: 20,
    label: "Mecânica auto",
    icon: '🚘',
    duration: '3 MESES',
    price: 2700,
    colors: ["gold"],
    plan: '',
    show: true,
  },
  {
    id: 21,
    label: "Educação de infância",
    icon: '🤱',
    duration: '3 MESES',
    price: 2700,
    colors: ["gold"],
    plan: '',
    show: true,
  },
];

const random = (n) => {
  return Math.round(Math.random() * n);
};


document.querySelector('title').innerText = 'Knowledge Center (KC)'